FROM node:20-alpine AS builder

WORKDIR /app

COPY ui/package.json ui/package-lock.json* ./
RUN npm ci

COPY ui ./

# Build
RUN npm run build

FROM caddy:2-alpine

COPY --from=builder /app/dist /usr/share/caddy

COPY ui/Caddyfile /etc/caddy/Caddyfile

EXPOSE 80

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]
