FROM golang:1.21-alpine AS builder

WORKDIR /app

# Install build dependencies
RUN apk add --no-cache git

# Copy go mod files
COPY smtp/go.mod smtp/go.sum ./
RUN go mod download

# Copy source code
COPY smtp ./

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o smtp ./main.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates tzdata

WORKDIR /root/

COPY --from=builder /app/smtp .

EXPOSE 25

CMD ["./smtp"]
